name: clang-format Check

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running clang-format Check
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '14'
        check-path: 'zns-tools.fs/src'
